spring.application.name=Student

spring.datasource.url=jdbc:postgresql://dpg-d7196boule4c73cok7m0-a.oregon-postgres.render.com:5432/student_7rkm
spring.datasource.username=student_7rkm_user
spring.datasource.password=hc6TqKqoaMx7mBOp73MeVOwsnWVc0pjo

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.sslmode=require
